[package]
name = "cuendillar"
version = "0.1.0"
edition = "2024"
description = "Embedded persistent key–value storage engine (LSM-tree based)"
license = "MIT"
repository = "https://github.com/Lovepreet67/cuendillar"
documentation = "https://docs.rs/cuendillar"
readme = "README.md"
keywords = ["database", "kv-store", "lsm", "storage", "embedded"]
categories = ["database-implementations", "kv-store"]
include = [
    "src/**/*",
    "benches/**/*",
    "tests/**/*",
    "LICENSE",
    "README.md",
    "Cargo.toml",
    "workload/sample.txt",
    "default_config.toml",
]


[dependencies]
byteorder = "1.5.0"
uuid = { version = "1.19.0", features = ["v4"] }
murmur3 = "0.5.2"
figment = { version = "0.10.19", features = ["toml"] }
serde = { version = "1.0.228", features = ["derive"] }
crc = "3.4.0"
tracing = "0.1.41"

[dev-dependencies]
criterion = "0.8.1"
tempfile = "3.24.0"
hdrhistogram = "7.5.4"
plotters = "0.3.7"
chrono = "0.4.42"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "json"] }

[[bench]]
name = "db_workload_operation"
path = "benches/db_operation_latency.rs"
harness = false

[[bench]]
name = "db_workload_operation_summerize"
path = "benches/db_operation_latency_summerize.rs"
harness = false

[[bench]]
name = "db_bench_rocksdb_compatible"
path = "benches/db_bench_rocksdb_compatible/main.rs"
harness = false


[profile.bench]
debug = true

[profile.release]
debug = false
