root_dir = "./table"

[wal]
variant = "default"
wal_dir = "./table/wal"
wal_group_sync_size = 100
wal_file_size_in_bytes = 200_00_00_0
wal_max_payload_len_in_bytes = 1000_000 # 1 MB

[memtable]
variant = "vector"
manager_variant = "default"
max_memtable_size = 1000

[sstable]
variant = "default"

[bloom]
variant = "default"
bits_per_key = 100
size = 1000

[index]
variant = "default"
index_block_min_size = 1000


[compaction]
root_dir = "./table"
compaction_interval = 100
min_l0_file_count = 3
variant = "leveled"
base_entries_per_table = 100
level_entries_growth_factor = 4
level_size_growth_factor = 4
level_base_size = 10000
max_level_count = 5

[cleaning]
cleaning_interval = 100
